---
- name: deploy on ci
  hosts: ci
  become: true
  tasks:
  
    - name: get artifact from Artifacorty
      get_url:
          dest: /tmp
          url: http://admin:password@18.207.221.194:8081/artifactory/libs-snapshot-local/org/springframework/boot/spring-boot-smoke-test-web-ui/2.2.0.BUILD-SNAPSHOT/spring-boot-smoke-test-web-ui-{{BUILD_NUMBER}}.jar
          # username: admin
          # password: password
          mode: 0755
          group: ubuntu
          owner: ubuntu

    - name: run java app
      become: true
      shell: java -jar /tmp/spring-boot-smoke-test-web-ui-{{ BUILD_NUMBER }}.jar --server.port={{ PORT_NUMBER | default('8080') }}
      async: 360
      poll: 0
